packages:
  - packages/*
  - examples/*
  - apps/*
allowBuilds:
  esbuild: true
minimumReleaseAgeExclude:
  - bluefish-js@0.0.39
  - bluefish-solid@0.0.39
  - '@umwelt-data/umwelt-utils@0.1.1'
  - '@umwelt-data/umwelt-utils@0.1.2'
  - '@umwelt-data/umwelt-utils@0.1.3'
  - '@umwelt-data/umwelt-utils@0.1.4'
  - '@umwelt-data/umwelt-utils@0.1.5'
  - '@umwelt-data/umwelt-utils@0.2.0'

