/**
 * Regenerate `apps/docs/api/` from the typedoc comments of every olli-solid
 * package, plus a sidebar fragment at `apps/docs/.vitepress/sidebar.api.ts`
 * consumed by the VitePress config.
 *
 * Run via `pnpm --filter docs build:api`. `apps/docs/api/` and
 * `.vitepress/sidebar.api.ts` are git-ignored; this script is the source of truth.
 *
 * We shell out to the typedoc CLI per package rather than driving typedoc
 * programmatically, because `Application.bootstrapWithPlugins` does not
 * reliably switch the renderer to typedoc-plugin-markdown's theme in
 * typedoc@0.28 + typedoc-plugin-markdown@4.11. CLI invocation is the
 * documented path and activates the plugin theme correctly.
 */

import { fileURLToPath } from 'node:url';
import { dirname, relative, resolve } from 'node:path';
import { rm, writeFile } from 'node:fs/promises';
import { spawn } from 'node:child_process';

const scriptDir = dirname(fileURLToPath(import.meta.url));
const DOCS_ROOT = resolve(scriptDir, '..');
const REPO_ROOT = resolve(DOCS_ROOT, '../..');
const PACKAGES_DIR = resolve(REPO_ROOT, 'packages');
const API_OUT_DIR = resolve(DOCS_ROOT, 'api');
const SIDEBAR_OUT_FILE = resolve(DOCS_ROOT, '.vitepress', 'sidebar.api.ts');

interface PackageSpec {
  name: string;
  group: 'Public API' | 'Domains' | 'Internals';
  label?: string;
}

const PACKAGES: PackageSpec[] = [
  { name: 'olli-js', group: 'Public API' },
  { name: 'olli-vis', group: 'Domains' },
  { name: 'olli-diagram', group: 'Domains' },
  { name: 'olli-core', group: 'Internals' },
  { name: 'olli-render-solid', group: 'Internals' },
  { name: 'olli-adapters', group: 'Internals' },
];

const TYPEDOC_COMMON_ARGS = [
  '--plugin', 'typedoc-plugin-markdown',
  '--readme', 'none',
  '--excludeInternal',
  '--excludePrivate',
  '--excludeProtected',
  '--skipErrorChecking',
  '--disableSources',
  '--hideBreadcrumbs',
  '--hidePageHeader',
  '--useCodeBlocks',
  '--expandObjects',
  '--entryFileName', 'index.md',
  '--fileExtension', '.md',
  '--logLevel', 'Warn',
];

function buildOne(pkg: PackageSpec): Promise<string> {
  const pkgRoot = resolve(PACKAGES_DIR, pkg.name);
  const entry = resolve(pkgRoot, 'src/index.ts');
  const outDir = resolve(API_OUT_DIR, pkg.name);

  const args = [
    ...TYPEDOC_COMMON_ARGS,
    '--tsconfig', resolve(pkgRoot, 'tsconfig.json'),
    '--out', outDir,
    entry,
  ];

  return new Promise((res, rej) => {
    const child = spawn('typedoc', args, {
      cwd: DOCS_ROOT,
      stdio: ['ignore', 'pipe', 'pipe'],
      env: { ...process.env, NODE_OPTIONS: '' },
    });
    let stderr = '';
    child.stdout.on('data', () => {});
    child.stderr.on('data', (d: Buffer) => (stderr += d.toString()));
    child.on('error', rej);
    child.on('exit', (code) => {
      if (code !== 0) {
        rej(new Error(`typedoc exited ${code} for ${pkg.name}\n${stderr}`));
      } else {
        res(relative(DOCS_ROOT, outDir));
      }
    });
  });
}

async function writeSidebarFragment(): Promise<void> {
  const byGroup = new Map<string, PackageSpec[]>();
  for (const pkg of PACKAGES) {
    const list = byGroup.get(pkg.group) ?? [];
    list.push(pkg);
    byGroup.set(pkg.group, list);
  }

  const groups = ['Public API', 'Domains', 'Internals'] as const;
  const entries = groups
    .filter((g) => byGroup.has(g))
    .map((g) => {
      const items = byGroup.get(g)!.map((p) => ({
        text: p.label ?? p.name,
        link: `/api/${p.name}/`,
      }));
      return {
        text: g,
        collapsed: g === 'Internals',
        items,
      };
    });

  const contents = `// AUTO-GENERATED by apps/docs/scripts/build-typedoc.ts — do not edit by hand.
import type { DefaultTheme } from 'vitepress';

export const apiSidebar: DefaultTheme.SidebarItem[] = ${JSON.stringify(entries, null, 2)};
`;
  await writeFile(SIDEBAR_OUT_FILE, contents, 'utf8');
}

async function writeApiLanding(): Promise<void> {
  const sections: string[] = [
    '---\ntitle: API reference\n---\n',
    '# API reference\n',
    'Auto-generated from TSDoc comments in the olli-solid packages. Regenerated on every build; do not edit files under `/api/` by hand.\n',
  ];

  const byGroup = new Map<string, PackageSpec[]>();
  for (const pkg of PACKAGES) {
    const list = byGroup.get(pkg.group) ?? [];
    list.push(pkg);
    byGroup.set(pkg.group, list);
  }

  for (const g of ['Public API', 'Domains', 'Internals'] as const) {
    const pkgs = byGroup.get(g);
    if (!pkgs?.length) continue;
    sections.push(`## ${g}\n`);
    for (const p of pkgs) {
      sections.push(`- [${p.name}](./${p.name}/)`);
    }
    sections.push('');
  }

  await writeFile(resolve(API_OUT_DIR, 'index.md'), sections.join('\n'), 'utf8');
}

async function main(): Promise<void> {
  await rm(API_OUT_DIR, { recursive: true, force: true });

  for (const pkg of PACKAGES) {
    process.stdout.write(`  typedoc ${pkg.name} ... `);
    const rel = await buildOne(pkg);
    process.stdout.write(`${rel}\n`);
  }

  await writeApiLanding();
  await writeSidebarFragment();
  process.stdout.write(`  sidebar -> ${relative(DOCS_ROOT, SIDEBAR_OUT_FILE)}\n`);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
